import type { MarketplaceItem } from "./types";

export const items: MarketplaceItem[] = [
	// Classic Collection (Unsplash)
	{
		id: "item-001",
		name: "Classic Leather Jacket",
		description:
			"Timeless black leather motorcycle jacket with asymmetric zip closure",
		category: "outerwear",
		brand: "Heritage & Co",
		price: 0.05,
		imageUrl: "https://images.unsplash.com/photo-1551028719-00167b16eac5",
		available: true,
		metadata: {
			size: ["S", "M", "L", "XL"],
			color: ["Black"],
			material: "Genuine Leather",
		},
	},
	{
		id: "item-002",
		name: "Vintage Denim Jacket",
		description: "Distressed light blue denim jacket with classic fit",
		category: "outerwear",
		brand: "Vintage Co",
		price: 0.03,
		imageUrl: "https://images.unsplash.com/photo-1576995853123-5a10305d93c0",
		available: true,
		metadata: {
			size: ["S", "M", "L"],
			color: ["Light Blue"],
			material: "100% Cotton Denim",
		},
	},
	{
		id: "item-003",
		name: "White Canvas Sneakers",
		description: "Minimalist low-top sneakers in premium white canvas",
		category: "footwear",
		brand: "Urban Stride",
		price: 0.02,
		imageUrl: "https://images.unsplash.com/photo-1549298916-b41d501d3772",
		available: true,
		metadata: {
			size: ["7", "8", "9", "10", "11", "12"],
			color: ["White"],
			material: "Canvas",
		},
	},
	{
		id: "item-004",
		name: "Black Chelsea Boots",
		description: "Classic leather Chelsea boots with elastic side panels",
		category: "footwear",
		brand: "Heritage & Co",
		price: 0.04,
		imageUrl: "https://images.unsplash.com/photo-1608256246200-53e635b5b65f",
		available: true,
		metadata: {
			size: ["7", "8", "9", "10", "11", "12"],
			color: ["Black"],
			material: "Full Grain Leather",
		},
	},
	{
		id: "item-005",
		name: "Cashmere Sweater",
		description: "Luxurious navy blue crew neck sweater in pure cashmere",
		category: "tops",
		brand: "Luxury Knits",
		price: 0.05,
		imageUrl: "https://images.unsplash.com/photo-1620799140408-edc6dcb6d633",
		available: true,
		metadata: {
			size: ["S", "M", "L", "XL"],
			color: ["Navy Blue"],
			material: "100% Cashmere",
		},
	},
	{
		id: "item-006",
		name: "Tailored Wool Trousers",
		description: "Charcoal grey wool blend trousers with classic fit",
		category: "bottoms",
		brand: "Formal House",
		price: 0.03,
		imageUrl: "https://images.unsplash.com/photo-1624378439575-d8705ad7ae80",
		available: true,
		metadata: {
			size: ["30", "32", "34", "36", "38"],
			color: ["Charcoal Grey"],
			material: "Wool Blend",
		},
	},
	{
		id: "item-007",
		name: "Silk Scarf",
		description: "Hand-rolled silk scarf with geometric pattern",
		category: "accessories",
		brand: "Luxury House",
		price: 0.04,
		imageUrl: "https://images.unsplash.com/photo-1601924994987-69e26d50dc26",
		available: true,
		metadata: {
			color: ["Multi"],
			material: "100% Silk",
		},
	},
	{
		id: "item-008",
		name: "Leather Crossbody Bag",
		description: "Compact leather crossbody bag in cognac brown",
		category: "accessories",
		brand: "Heritage & Co",
		price: 0.04,
		imageUrl: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa",
		available: true,
		metadata: {
			color: ["Cognac Brown"],
			material: "Full Grain Leather",
		},
	},
	{
		id: "item-009",
		name: "Merino Wool Cardigan",
		description: "Lightweight grey cardigan in merino wool",
		category: "tops",
		brand: "Luxury Knits",
		price: 0.03,
		imageUrl: "https://images.unsplash.com/photo-1434389677669-e08b4cac3105",
		available: true,
		metadata: {
			size: ["S", "M", "L", "XL"],
			color: ["Grey"],
			material: "100% Merino Wool",
		},
	},
	{
		id: "item-010",
		name: "Slim Fit Chinos",
		description: "Modern slim-fit chinos in khaki",
		category: "bottoms",
		brand: "Urban Stride",
		price: 0.01,
		imageUrl: "https://images.unsplash.com/photo-1473966968600-fa801b869a1a",
		available: true,
		metadata: {
			size: ["30", "32", "34", "36", "38"],
			color: ["Khaki"],
			material: "Cotton Twill",
		},
	},

	// Festival Collection
	{
		id: "festival-top-001",
		name: "Holographic Crop Top",
		description:
			"Vibrant holographic top in purple and orange colors, perfect for festivals and raves",
		category: "tops",
		brand: "Festival Collective",
		price: 0.03,
		imageUrl: "/festival-items/festival-top-001.webp",
		available: true,
		metadata: {
			size: ["XS", "S", "M", "L", "XL"],
			color: ["purple", "orange"],
			material: "Holographic Fabric",
		},
	},
	{
		id: "festival-top-002",
		name: "Mesh Festival Tank",
		description:
			"Vibrant mesh top in red and yellow colors, perfect for festivals and raves",
		category: "tops",
		brand: "Festival Collective",
		price: 0.03,
		imageUrl: "/festival-items/festival-top-002.webp",
		available: true,
		metadata: {
			size: ["XS", "S", "M", "L", "XL"],
			color: ["red", "yellow"],
			material: "Breathable Mesh",
		},
	},
	{
		id: "festival-outerwear-001",
		name: "LED Light-Up Jacket",
		description:
			"Vibrant led futuristic outerwear in red, yellow, purple and orange colors, perfect for festivals and raves",
		category: "outerwear",
		brand: "Festival Collective",
		price: 0.05,
		imageUrl: "/festival-items/festival-outerwear-001.webp",
		available: true,
		metadata: {
			size: ["S", "M", "L", "XL"],
			color: ["red", "yellow", "purple", "orange"],
			material: "LED-Integrated Fabric",
		},
	},
	{
		id: "festival-top-003",
		name: "Sequin Festival Top",
		description:
			"Vibrant sequin sparkle top in orange and purple colors, perfect for festivals and raves",
		category: "tops",
		brand: "Festival Collective",
		price: 0.03,
		imageUrl: "/festival-items/festival-top-003.webp",
		available: true,
		metadata: {
			size: ["XS", "S", "M", "L", "XL"],
			color: ["orange", "purple"],
			material: "Sequin Fabric",
		},
	},
	{
		id: "festival-top-004",
		name: "Metallic Bodysuit Top",
		description:
			"Vibrant metallic futuristic top in yellow and red colors, perfect for festivals and raves",
		category: "tops",
		brand: "Festival Collective",
		price: 0.03,
		imageUrl: "/festival-items/festival-top-004.webp",
		available: true,
		metadata: {
			size: ["XS", "S", "M", "L", "XL"],
			color: ["yellow", "red"],
			material: "Metallic Fabric",
		},
	},
	{
		id: "festival-bottom-001",
		name: "Neon Rave Pants",
		description:
			"Vibrant neon wide-leg bottom in purple and yellow colors, perfect for festivals and raves",
		category: "bottoms",
		brand: "Festival Collective",
		price: 0.03,
		imageUrl: "/festival-items/festival-bottom-001.webp",
		available: true,
		metadata: {
			size: ["XS", "S", "M", "L", "XL"],
			color: ["purple", "yellow"],
			material: "UV-Reactive Fabric",
		},
	},
	{
		id: "festival-bottom-002",
		name: "Holographic Festival Shorts",
		description:
			"Vibrant holographic shorts bottom in orange and red colors, perfect for festivals and raves",
		category: "bottoms",
		brand: "Festival Collective",
		price: 0.03,
		imageUrl: "/festival-items/festival-bottom-002.webp",
		available: true,
		metadata: {
			size: ["XS", "S", "M", "L", "XL"],
			color: ["orange", "red"],
			material: "Holographic Fabric",
		},
	},
	{
		id: "festival-bottom-003",
		name: "LED Strip Leggings",
		description:
			"Vibrant led futuristic bottom in red, yellow, purple and orange colors, perfect for festivals and raves",
		category: "bottoms",
		brand: "Festival Collective",
		price: 0.03,
		imageUrl: "/festival-items/festival-bottom-003.webp",
		available: true,
		metadata: {
			size: ["XS", "S", "M", "L", "XL"],
			color: ["red", "yellow", "purple", "orange"],
			material: "LED-Integrated Fabric",
		},
	},
	{
		id: "festival-bottom-004",
		name: "Festival Fringe Skirt",
		description:
			"Vibrant fringe flowing bottom in red and purple colors, perfect for festivals and raves",
		category: "bottoms",
		brand: "Festival Collective",
		price: 0.03,
		imageUrl: "/festival-items/festival-bottom-004.webp",
		available: true,
		metadata: {
			size: ["XS", "S", "M", "L", "XL"],
			color: ["red", "purple"],
			material: "Fringe Fabric",
		},
	},
	{
		id: "festival-shoes-001",
		name: "LED Platform Boots",
		description:
			"Vibrant platform led shoes in purple and yellow colors, perfect for festivals and raves",
		category: "footwear",
		brand: "Festival Collective",
		price: 0.04,
		imageUrl: "/festival-items/festival-shoes-001.webp",
		available: true,
		metadata: {
			size: ["7", "8", "9", "10", "11", "12"],
			color: ["purple", "yellow"],
			material: "LED-Integrated Fabric",
		},
	},
	{
		id: "festival-accessory-001",
		name: "Glow Accessories Pack",
		description:
			"Vibrant glow neon accessory in red, yellow, purple and orange colors, perfect for festivals and raves",
		category: "accessories",
		brand: "Festival Collective",
		price: 0.02,
		imageUrl: "/festival-items/festival-accessory-001.webp",
		available: true,
		metadata: {
			color: ["red", "yellow", "purple", "orange"],
			material: "UV-Reactive Fabric",
		},
	},
	{
		id: "festival-accessory-002",
		name: "Holographic Festival Bag",
		description:
			"Vibrant holographic bag accessory in orange and purple colors, perfect for festivals and raves",
		category: "accessories",
		brand: "Festival Collective",
		price: 0.02,
		imageUrl: "/festival-items/festival-accessory-002.webp",
		available: true,
		metadata: {
			color: ["orange", "purple"],
			material: "Holographic Fabric",
		},
	},
	{
		id: "festival-accessory-003",
		name: "LED Flower Crown",
		description:
			"Vibrant led headpiece accessory in red and yellow colors, perfect for festivals and raves",
		category: "accessories",
		brand: "Festival Collective",
		price: 0.02,
		imageUrl: "/festival-items/festival-accessory-003.webp",
		available: true,
		metadata: {
			color: ["red", "yellow"],
			material: "LED-Integrated Fabric",
		},
	},
	{
		id: "festival-dress-001",
		name: "Festival Bodysuit",
		description:
			"Vibrant bodysuit colorful dress in red, yellow, purple and orange colors, perfect for festivals and raves",
		category: "dresses",
		brand: "Festival Collective",
		price: 0.04,
		imageUrl: "/festival-items/festival-dress-001.webp",
		available: true,
		metadata: {
			size: ["XS", "S", "M", "L", "XL"],
			color: ["red", "yellow", "purple", "orange"],
			material: "Synthetic Blend",
		},
	},
	{
		id: "festival-dress-002",
		name: "Rave Dress with Cutouts",
		description:
			"Vibrant dress cutout dress in purple and orange colors, perfect for festivals and raves",
		category: "dresses",
		brand: "Festival Collective",
		price: 0.04,
		imageUrl: "/festival-items/festival-dress-002.webp",
		available: true,
		metadata: {
			size: ["XS", "S", "M", "L", "XL"],
			color: ["purple", "orange"],
			material: "Synthetic Blend",
		},
	},
	{
		id: "festival-dress-003",
		name: "Holographic Romper",
		description:
			"Vibrant holographic romper dress in yellow and red colors, perfect for festivals and raves",
		category: "dresses",
		brand: "Festival Collective",
		price: 0.04,
		imageUrl: "/festival-items/festival-dress-003.webp",
		available: true,
		metadata: {
			size: ["XS", "S", "M", "L", "XL"],
			color: ["yellow", "red"],
			material: "Holographic Fabric",
		},
	},
	{
		id: "festival-dress-004",
		name: "Festival Jumpsuit",
		description:
			"Vibrant jumpsuit bold dress in red and purple colors, perfect for festivals and raves",
		category: "dresses",
		brand: "Festival Collective",
		price: 0.04,
		imageUrl: "/festival-items/festival-dress-004.webp",
		available: true,
		metadata: {
			size: ["XS", "S", "M", "L", "XL"],
			color: ["red", "purple"],
			material: "Synthetic Blend",
		},
	},
];
