import type { MarketplaceItem } from "./types"

export const items: MarketplaceItem[] = [
	{
		id: "item-001",
		name: "Classic Leather Jacket",
		description:
			"Timeless black leather motorcycle jacket with asymmetric zip closure",
		category: "outerwear",
		brand: "Heritage & Co",
		price: 299.99,
		imageUrl: "https://images.unsplash.com/photo-1551028719-00167b16eac5",
		available: true,
		metadata: {
			size: ["S", "M", "L", "XL"],
			color: ["Black"],
			material: "Genuine Leather",
		},
	},
	{
		id: "item-002",
		name: "Vintage Denim Jacket",
		description: "Distressed light blue denim jacket with classic fit",
		category: "outerwear",
		brand: "Vintage Co",
		price: 89.99,
		imageUrl: "https://images.unsplash.com/photo-1576995853123-5a10305d93c0",
		available: true,
		metadata: {
			size: ["S", "M", "L"],
			color: ["Light Blue"],
			material: "100% Cotton Denim",
		},
	},
	{
		id: "item-003",
		name: "White Canvas Sneakers",
		description: "Minimalist low-top sneakers in premium white canvas",
		category: "footwear",
		brand: "Urban Stride",
		price: 79.99,
		imageUrl: "https://images.unsplash.com/photo-1549298916-b41d501d3772",
		available: true,
		metadata: {
			size: ["7", "8", "9", "10", "11", "12"],
			color: ["White"],
			material: "Canvas",
		},
	},
	{
		id: "item-004",
		name: "Black Chelsea Boots",
		description: "Classic leather Chelsea boots with elastic side panels",
		category: "footwear",
		brand: "Heritage & Co",
		price: 189.99,
		imageUrl: "https://images.unsplash.com/photo-1608256246200-53e635b5b65f",
		available: true,
		metadata: {
			size: ["7", "8", "9", "10", "11", "12"],
			color: ["Black"],
			material: "Full Grain Leather",
		},
	},
	{
		id: "item-005",
		name: "Cashmere Sweater",
		description: "Luxurious navy blue crew neck sweater in pure cashmere",
		category: "tops",
		brand: "Luxury Knits",
		price: 249.99,
		imageUrl: "https://images.unsplash.com/photo-1620799140408-edc6dcb6d633",
		available: true,
		metadata: {
			size: ["S", "M", "L", "XL"],
			color: ["Navy Blue"],
			material: "100% Cashmere",
		},
	},
	{
		id: "item-006",
		name: "Tailored Wool Trousers",
		description: "Charcoal grey wool blend trousers with classic fit",
		category: "bottoms",
		brand: "Formal House",
		price: 129.99,
		imageUrl: "https://images.unsplash.com/photo-1624378439575-d8705ad7ae80",
		available: true,
		metadata: {
			size: ["30", "32", "34", "36", "38"],
			color: ["Charcoal Grey"],
			material: "Wool Blend",
		},
	},
	{
		id: "item-007",
		name: "Silk Scarf",
		description: "Hand-rolled silk scarf with geometric pattern",
		category: "accessories",
		brand: "Luxury House",
		price: 159.99,
		imageUrl: "https://images.unsplash.com/photo-1601924994987-69e26d50dc26",
		available: true,
		metadata: {
			color: ["Multi"],
			material: "100% Silk",
		},
	},
	{
		id: "item-008",
		name: "Leather Crossbody Bag",
		description: "Compact leather crossbody bag in cognac brown",
		category: "accessories",
		brand: "Heritage & Co",
		price: 199.99,
		imageUrl: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa",
		available: true,
		metadata: {
			color: ["Cognac Brown"],
			material: "Full Grain Leather",
		},
	},
	{
		id: "item-009",
		name: "Merino Wool Cardigan",
		description: "Lightweight grey cardigan in merino wool",
		category: "tops",
		brand: "Luxury Knits",
		price: 179.99,
		imageUrl: "https://images.unsplash.com/photo-1434389677669-e08b4cac3105",
		available: true,
		metadata: {
			size: ["S", "M", "L", "XL"],
			color: ["Grey"],
			material: "100% Merino Wool",
		},
	},
	{
		id: "item-010",
		name: "Slim Fit Chinos",
		description: "Modern slim-fit chinos in khaki",
		category: "bottoms",
		brand: "Urban Stride",
		price: 69.99,
		imageUrl: "https://images.unsplash.com/photo-1473966968600-fa801b869a1a",
		available: true,
		metadata: {
			size: ["30", "32", "34", "36", "38"],
			color: ["Khaki"],
			material: "Cotton Twill",
		},
	},
]
